baseURL: https://quid-agis.netlify.app/
languageCode: en-us
title: Archie
theme: archie
copyright: Â© Athul
pygmentsstyle: monokai
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
ignoreErrors: "error-missing-instagram-accesstoken"
params:
  mode: auto
  social:
    - icon: github
      name: GitHub
      url: https://github.com/athusdfsdfsdfl/archie
    - icon: twitter
      name: Twitter
      url: https://github.com/athulcajay/
    - icon: gitlab
      name: GitLab
      url: https://gitlab.com/athul/
  subtitle: Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)
  useCDN: no
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 3
    - name: Tags
      url: /tags
      weight: 4
