baseURL: https://quid-agis.netlify.app/
languageCode: en-us
title: The Blog of Quid Agis
theme: archie
copyright: Â© Quid Agis 
pygmentsstyle: monokai
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
ignoreErrors: "error-missing-instagram-accesstoken"
params:
  mode: auto
  social:
    - icon: github
      name: GitHub
      url: https://github.com/quid-agis
    - icon: twitter
      name: Twitter
      url: https://twitter.com/quid_agis_2713
  subtitle: Writing about Technology and my efforts to not break it.
  useCDN: no
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 3
    - name: Tags
      url: /tags
      weight: 4
